# Generated by Django 3.1.7 on 2021-02-21 12:09

from django.db import migrations


def make_my_tasks_position(apps, schema_editor):
    User = apps.get_model("users", "User")
    Lesson = apps.get_model("lessons", "Lesson")

    from django.contrib.auth.hashers import make_password

    usernames = ["vasya_pupkin", "manager1", "manager2", "manager3", "petya_ivanov"]
    lessons_names = ["Русский", "Обществознание", "Математика"]

    User.objects.bulk_create(
        [
            User(
                username=name,
                first_name=name,
                email="test@email.com",
                password=make_password("HARDpasw213"),
                is_active=True,
            )
            for name in usernames
        ]
    )

    Lesson.objects.bulk_create([Lesson(name=lesson) for lesson in lessons_names])


class Migration(migrations.Migration):
    dependencies = [("users", "0001_initial")]

    operations = [migrations.RunPython(make_my_tasks_position)]
