version: '3.7'

volumes:
  postgres:
  redis:

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=django-channels
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "python3 manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  redis:
    image: redis:6.0.6-alpine
    volumes:
      - redis/:/data
    command: redis-server
    ports:
      - 6379